development:
  host: localhost
  database: davinci_development
  
semi_production:
  host: localhost
  database: davinci_development

test:
  host: localhost
  database: davinci_test

production:
  uri: <%= ENV['MONGOLAB_URI'] %>

demo:
  uri: <%= ENV['MONGOLAB_URI'] %>
